project_id = "couple-menu-pwa"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 17

[studio]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"
enable_signup = false

[storage]
enabled = true
file_size_limit = "12MiB"
